### ISSUE TITLE
Read only access on medium.com domain and optionally grant permissions for all sites

### ISSUE THREAD

**Issue by ttuygun** [Gyvastis/chrome-medium-unlimited-reading#3]

**Comment by Gyvastis** [comment]
Hi. I'm not sure there's such a thing as read only access and it wouldn't work with this extension. If it's read-only, how do you expect the content to be updated? On the second part I do agree, optional permissions might be a good solution to make it less scary for people to use this extension (even though it's open source). Thanks for the suggestions.
